### ISSUE TITLE
Vouchers Return ID , TYPE e VALOR

### ISSUE THREAD

**Issue by henriquelcardoso** [tiagoCMatias/AcmeCafe#4]
No get dos vouchers do User, returnar um ID do voucher como Int baixo (ex:1), o type que foi inserido, pode ser como String que é só para apresentar e um Valor como Double que num vai ser o valor ou percentagem a ser retirada ao preço, mas pode ser sempre um double (Quando é um free coffee o Valor é 0.9 acho eu, se for o dos 5% o valor é 0.05).

**Comment by tiagoCMatias** [comment]
Done
